--ozone-platform-hint=auto
--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiIgnoreDriverChecks
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--password-store=kwallet6
